# Makefile for tcl vivado project
# blink-led
# Tom Trebisky  1-6-2025

all:
	@echo "Sorry, be more specific"

project:
	vivado -mode batch -source mk_proj.tcl

build:
	vivado -mode batch -source build.tcl

clean:
	rm -f *.jou
	rm -f *.log
	rm -rf .Xil
	rm -rf blink-led

